[build-system]
requires = ["setuptools==82.0.0", "setuptools-scm==9.2.2"]
build-backend = "setuptools.build_meta"

[project]
name = "gitrole"
requires-python = ">= 3.11, < 3.15"
authors = [{ name = "qqfunc", email = "qqfunc@gmail.com" }]
description = "Switch between Git configurations based on role."
readme = "README.md"
license = "Unlicense"
license-files = ["LICENSE.md"]
keywords = ["git"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Software Development :: Version Control :: Git",
  "Typing :: Typed",
]
dynamic = ["version"]
dependencies = [
  "filelock~=3.24.0",
  "pygit2~=1.19.0",
  "pyyaml~=6.0.3",
]

[project.scripts]
gitrole = "gitrole.__main__:main"

[project.urls]
Source = "https://www.github.com/qqfunc/gitrole"
Issues = "https://www.github.com/qqfunc/gitrole/issues"

[dependency-groups]
dev = [
  "commitlint==1.13.3",
  "editorconfig-checker==3.6.0",
  "lefthook==2.0.15",
  "ruff==0.15.4",
  "ty==0.0.1a25",
  "typos==1.44.0",
]

[tool.pytest.ini_options]
addopts = "-n auto"

[tool.ruff]
line-length = 79
format.docstring-code-line-length = 72
lint.select = ["ALL"]
lint.ignore = [
  "PYI021", # docstring-in-stub
  "D203",   # one-blank-line-before-class
  "D213",   # multi-line-summary-second-line
  "D418",   # overload-with-docstring
]
lint.per-file-ignores."tests/**.py" = [
  "S101",    # assert
  "INP001",  # implicit-namespace-package
  "PLR2004", # magic-value-comparison
]
lint.pycodestyle.max-doc-length = 72

[tool.setuptools_scm]

[tool.ty]
terminal.error-on-warning = true

[tool.typos]
files.extend-exclude = ["uv.lock"]
default.unicode = false
